# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Algorithm name')),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateTimeField(verbose_name='date experimented')),
                ('parameter', models.TextField(verbose_name='parameters used')),
                ('result', models.TextField(verbose_name='result used')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='ExpTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('has_experiments', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=20)),
                ('server_ip', models.GenericIPAddressField()),
                ('server_cpu', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('deadline_date', models.DateTimeField(verbose_name='')),
                ('completed_date', models.DateTimeField(null=True)),
                ('done', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Project')),
            ],
        ),
        migrations.AddField(
            model_name='exptodo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Project'),
        ),
        migrations.AddField(
            model_name='expitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Project'),
        ),
    ]
