# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0003_auto_20160723_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_synthetic', models.BooleanField(default=False)),
                ('synthetic_parameters', models.TextField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='expitem',
            name='result',
            field=models.TextField(verbose_name='result'),
        ),
        migrations.AddField(
            model_name='expitem',
            name='dataset',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='projectManager.Dataset'),
            preserve_default=False,
        ),
    ]
