# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0004_auto_20160723_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expitem',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManager.Dataset'),
        ),
    ]
