# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0008_project_experiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='experiment',
            new_name='experimentParams',
        ),
    ]
