# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0009_auto_20160724_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resultFilter',
            field=models.TextField(null=True),
        ),
    ]
