# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0010_project_resultfilter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='experimentParams',
            new_name='paramFilter',
        ),
    ]
