# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0011_auto_20160728_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='status',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
