# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0012_algorithm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expitem',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='failed'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deadline_date',
            field=models.DateTimeField(verbose_name='deadline date'),
        ),
    ]
