# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0013_auto_20160802_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
