# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0014_relatedworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedworks',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectManager.Project'),
            preserve_default=False,
        ),
    ]
