# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0015_relatedworks_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedWorks',
            new_name='RelatedWork',
        ),
    ]
