# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0017_expitem_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expitem',
            name='server',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManager.Server'),
        ),
    ]
