# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0018_auto_20160805_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='expitem',
            name='invalid',
            field=models.BooleanField(default=False, verbose_name='invalid'),
        ),
    ]
