# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0022_dataset_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedwork',
            name='pdf_path',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
