# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0024_auto_20160816_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedwork',
            name='journal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='relatedwork',
            name='title',
            field=models.TextField(default='Title'),
            preserve_default=False,
        ),
    ]
