# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0026_auto_20160817_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='paramFilter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='resultFilter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
