# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0027_auto_20160817_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('last_visit', models.DateTimeField(null=True)),
                ('times_visited', models.IntegerField(default=1)),
            ],
        ),
    ]
