# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0028_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='times_visited',
            field=models.IntegerField(default=0),
        ),
    ]
