# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0029_auto_20160817_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
