# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0030_auto_20160818_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('attachment', models.FileField(upload_to='')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Server')),
            ],
        ),
    ]
