# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0031_settingfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingfiles',
            name='hashcode',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
