# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0032_settingfiles_hashcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedwork',
            name='pdf_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
