# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0034_auto_20160831_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='expitem',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date uploaded'),
            preserve_default=False,
        ),
    ]
