# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-15 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0040_auto_20170715_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacontainment',
            name='dataset_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.DatasetList'),
        ),
    ]
