# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-15 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0045_auto_20170715_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataContainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Dataset')),
                ('dataset_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.DatasetList')),
            ],
        ),
    ]
