# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-15 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0047_auto_20170715_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacontainment',
            old_name='dataset_list',
            new_name='data_list',
        ),
        migrations.AlterField(
            model_name='datacontainment',
            name='data_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.DatasetList'),
        ),
    ]
