# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0054_auto_20170715_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='queryFilter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
