# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0055_project_queryfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summaryFilter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
