# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0056_project_summaryfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('data_file', models.FileField(null=True, upload_to='')),
                ('graph_file', models.FileField(null=True, upload_to='')),
                ('datalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.DataList')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.Project')),
            ],
        ),
    ]
