# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0057_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='plot_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
