# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0059_algorithm_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
