# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0060_auto_20170719_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='variable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
