# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0061_datalist_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
