# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0064_auto_20170725_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
