# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0065_server_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='repeat',
            field=models.IntegerField(default=3),
        ),
    ]
