# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0066_datalist_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='exptodo',
            name='datalist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectManager.DataList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exptodo',
            name='serverlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectManager.ServerList'),
            preserve_default=False,
        ),
    ]
