# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0068_auto_20170726_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exptodo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
