# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0069_auto_20170726_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exptodo',
            old_name='parameters',
            new_name='parameter',
        ),
    ]
