# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0072_auto_20170726_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='execute_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
