# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0075_exptodo_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='synthetic_parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
