# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0076_auto_20170821_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='initialize_code',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_setting_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
